version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=plentina
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - nestjs-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - nestjs-network
  
  plentina-api:
    container_name: 'plentina-api'
    image: plentina-api:1.0.0
    build:
      context: ../api
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 4000:4000
    networks:
      - nestjs-network
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mysql
  plentina-ui:
    container_name: 'plentina-ui'
    image: plentina-ui:1.0.0
    build:
      context: ../ui
      target: development
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    volumes:
      - ../ui:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - plentina-api
      - mysql

volumes:
  mysql:
  mysql_config:

networks:
  nestjs-network:
    driver: bridge